apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    sed 's/validationFailureAction: Audit/validationFailureAction: Enforce/' application-field-validation.yaml | kubectl create -f - 