---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: "1.23"
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/category: Argo
    policies.kyverno.io/description: This policy performs some best practices validation
      on Application fields. Path or chart must be specified but never both. And destination.name
      or destination.server must be specified but never both.
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Application
    policies.kyverno.io/title: Application Field Validation
  name: application-field-validation
spec:
  admission: true
  background: true
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Application
    name: source-path-chart
    validate:
      anyPattern:
      - spec:
          source:
            X(chart): null
            path: ?*
      - spec:
          source:
            X(path): null
            chart: ?*
      message: '`spec.source.path` OR `spec.source.chart` should be specified but
        never both.'
  - match:
      any:
      - resources:
          kinds:
          - Application
    name: destination-server-name
    validate:
      anyPattern:
      - spec:
          destination:
            X(name): null
            server: ?*
      - spec:
          destination:
            X(server): null
            name: ?*
      message: '`spec.destination.server` OR `spec.destination.name` should be specified
        but never both.'
  validationFailureAction: Audit
