# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: cleanup-empty-replicasets
spec:
  steps:
  - name: step-01
    try:
    - apply:
        file: ../cluster-role.yaml
  - name: step-02
    try:
    - apply:
        file: rs.yaml
    - assert:
        file: chainsaw-assert-1.yaml
  - name: step-03
    try:
    - apply:
        file: ../cleanup-empty-replicasets.yaml
    - assert:
        file: ../cleanup-empty-replicasets.yaml
  - name: step-04
    try:
    - sleep:
        duration: 1m5s
  - name: step-05
    try:
    - error:
        file: chainsaw-assert-1.yaml
