---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: "1.23"
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/category: Argo
    policies.kyverno.io/description: This policy prevents the use of the default project
      in an Application.
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Application
    policies.kyverno.io/title: Prevent Use of Default Project
  name: application-prevent-default-project
spec:
  admission: true
  background: true
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Application
    name: default-project
    preconditions:
      all:
      - key: '{{ request.operation || ''BACKGROUND'' }}'
        operator: NotEquals
        value: DELETE
    validate:
      message: The default project may not be used in an Application.
      pattern:
        spec:
          project: '!default'
  validationFailureAction: Audit
