apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    sed 's/validationFailureAction: Audit/validationFailureAction: Enforce/' appproject-clusterresourceblacklist.yaml | kubectl create -f - 