apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    sed 's/validationFailureAction: Audit/validationFailureAction: Enforce/' application-prevent-updates-project.yaml | kubectl create -f - 