---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: "1.23"
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/category: Argo
    policies.kyverno.io/description: This policy prevents updates to the project field
      after an Application is created.
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Application
    policies.kyverno.io/title: Prevent Updates to Project
  name: application-prevent-updates-project
spec:
  admission: true
  background: true
  rules:
  - match:
      any:
      - resources:
          kinds:
          - Application
    name: project-updates
    preconditions:
      all:
      - key: '{{ request.operation || ''BACKGROUND'' }}'
        operator: Equals
        value: UPDATE
    validate:
      deny:
        conditions:
          any:
          - key: '{{request.object.spec.project}}'
            operator: NotEquals
            value: '{{request.oldObject.spec.project}}'
      message: The spec.project cannot be changed once the Application is created.
  validationFailureAction: Audit
