apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: restrict-ingress-classes
policies:
- restrict-ingress-classes.yaml
resources:
- resource.yaml
results:
- kind: Ingress
  policy: default/restrict-ingress-classes
  resources:
  - minimal-ingress-2
  result: fail
  rule: validate-ingress
- kind: Ingress
  policy: default/restrict-ingress-classes
  resources:
  - minimal-ingress-1
  result: pass
  rule: validate-ingress
