apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: change-dns-config-policy
policies:
- dns-policy-and-dns-config.yaml
resources:
- resource.yaml
results:
- kind: Pod
  patchedResource: patchedResource.yaml
  policy: default/change-dns-config-policy
  resources:
  - myapp-pod
  result: pass
  rule: dns-policy
variables: variables.yaml
