name: "Runs E2E Tests"
description: "Runs E2E tests using chainsaw"
inputs:
  tests:
    description: "Test regex"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@b2f61a8d0459a65c476ac802514d88e1612b3396 # v0.2.9
      with:
        verify: true
    - name: Test with Chainsaw
      shell: bash
      run: |
        set -e
        chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ inputs.tests }}' --no-color=false
