name: "Runs E2E Tests"
description: "Runs E2E tests using chainsaw"
inputs:
  tests:
    description: "Test regex"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@d311eacde764f806c9658574ff64c9c3b21f8397 # v0.2.11
      with:
        verify: true
    - name: Test with Chainsaw
      shell: bash
      run: |
        set -e
        chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ inputs.tests }}' --no-color=false
