apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: add-pod-priorityclassname
policies:
- add-pod-priorityclassname.yaml
resources:
- resource.yaml
results:
- kind: Pod
  patchedResource: patchedResource.yaml
  policy: foo/add-pod-priorityclassname
  resources:
  - blank
  result: pass
  rule: add-priorityclass-pods
variables: values.yaml
