---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: "1.23"
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/category: Argo
    policies.kyverno.io/description: This policy ensures that the name of the ApplicationSet
      is the same value provided in the project.
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ApplicationSet
    policies.kyverno.io/title: Ensure ApplicationSet Name Matches Project
  name: applicationset-name-matches-project
spec:
  admission: true
  background: true
  rules:
  - match:
      any:
      - resources:
          kinds:
          - ApplicationSet
    name: match-name
    preconditions:
      all:
      - key: '{{ request.operation || ''BACKGROUND'' }}'
        operator: NotEquals
        value: DELETE
    validate:
      message: The name must match the project.
      pattern:
        spec:
          template:
            spec:
              project: '{{request.object.metadata.name}}'
  validationFailureAction: Audit
